from sqlalchemy import Column, Integer, String, Boolean, ForeignKey, Enum as SqEnum, UniqueConstraint, DateTime
from sqlalchemy.orm import relationship
from enum import Enum
import datetime
from core.database import Base

class UserRole(str, Enum):
    SUPERADMIN = "SUPERADMIN"
    TEACHER = "TEACHER"
    GROUP_CHIEF = "GROUP_CHIEF"
    TEAM_LEADER = "TEAM_LEADER"
    TEAM_MEMBER = "TEAM_MEMBER"

class GroupName(str, Enum):
    B = "B"
    D = "D"

class ScheduleState(str, Enum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    NONE = "NONE"

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, autoincrement=True)
    username = Column(String, unique=True, nullable=False)
    password_hash = Column(String, nullable=False)
    full_name = Column(String, nullable=False)
    role = Column(SqEnum(UserRole), nullable=False)

    # Relationships
    team_id = Column(Integer, ForeignKey("teams.id"), nullable=True)
    team = relationship("Team", back_populates="members")

    # Availabilities
    availabilities = relationship("Availability", back_populates="user", cascade="all, delete-orphan")

    # Group assignment (for GROUP_CHIEF and TEACHER roles)
    group_name = Column(SqEnum(GroupName), nullable=True)

class Team(Base):
    __tablename__ = "teams"

    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String, unique=True, nullable=False)
    group_name = Column(SqEnum(GroupName), nullable=False)

    # Locking availability submission
    is_locked = Column(Boolean, default=False)

    members = relationship("User", back_populates="team")
    reservations = relationship("Reservation", back_populates="team")

class Availability(Base):
    __tablename__ = "availabilities"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    day_of_week = Column(Integer, nullable=False)  # 0=Monday, 4=Friday
    period = Column(Integer, nullable=False)  # 1-9

    user = relationship("User", back_populates="availabilities")

    __table_args__ = (
        UniqueConstraint('user_id', 'day_of_week', 'period', name='_user_availability_uc'),
    )

class GroupBlock(Base):
    """Blocks theoretical class periods for an entire group (B or D)."""
    __tablename__ = "group_blocks"

    id = Column(Integer, primary_key=True, autoincrement=True)
    group_name = Column(SqEnum(GroupName), nullable=False)
    day_of_week = Column(Integer, nullable=False)
    period = Column(Integer, nullable=False)  # 1-9

    __table_args__ = (
        UniqueConstraint('group_name', 'day_of_week', 'period', name='_group_block_uc'),
    )

class RoboticsClassSchedule(Base):
    """
    Records which periods a teacher's robotics class occupies for a given group.
    These become hard constraints: the lab MUST be reserved for that group at these times.
    """
    __tablename__ = "robotics_class_schedule"

    id = Column(Integer, primary_key=True, autoincrement=True)
    teacher_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    group_name = Column(SqEnum(GroupName), nullable=False)
    day_of_week = Column(Integer, nullable=False)  # 0-4
    period = Column(Integer, nullable=False)  # 1-9

    teacher = relationship("User")

    __table_args__ = (
        UniqueConstraint('group_name', 'day_of_week', 'period', name='_robotics_class_uc'),
    )

class Reservation(Base):
    """
    Represents a scheduled slot for a team or a robotics class.
    Can be generated by GA, manually created, or from robotics class schedule.
    """
    __tablename__ = "reservations"

    id = Column(Integer, primary_key=True, autoincrement=True)
    team_id = Column(Integer, ForeignKey("teams.id"), nullable=True)
    day_of_week = Column(Integer, nullable=False)
    period = Column(Integer, nullable=False)  # 1-9

    is_manual = Column(Boolean, default=False)
    is_robotics_class = Column(Boolean, default=False)
    group_name = Column(SqEnum(GroupName), nullable=True)  # Set when is_robotics_class=True

    team = relationship("Team", back_populates="reservations")

    __table_args__ = (
        UniqueConstraint('day_of_week', 'period', name='_single_robot_slot_uc'),
    )

class SystemSetting(Base):
    __tablename__ = "system_settings"

    key = Column(String, primary_key=True)
    value = Column(String, nullable=False)

# Constants for System Settings Keys
KEY_FIRST_PERIOD = "first_period"  # '1' or '3'
KEY_MANUAL_MODE = "manual_mode"  # 'true' or 'false'
KEY_SCHEDULE_STATUS = "schedule_status"  # 'DRAFT' or 'PUBLISHED'
